package domains

units: [
	{name: "ValidKubeBundle", worth: 500, isA: ["UnaryPred", "Pred", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["Anything"], arity: 1, defn: "kube-bundle-valid?"},
	{name: "ValidKubeRepairValue", worth: 500, isA: ["UnaryPred", "Pred", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["Anything"], arity: 1, defn: "kube-repair-value-valid?"},
	{name: "KubeValueMatches", worth: 500, isA: ["BinaryPred", "Pred", "Op", "Anything"], domain: ["KubeRepairValue", "KubeRepairValue"], range: ["Anything"], arity: 2, defn: "kube-value-matches?"},

	{name: "KubeFeaturePutTemplateFromDeployment", worth: 500, isA: ["KubeRepairFeature", "Anything"], creditFeatureKey: "kube-feature/v1|put-label|template-label|deployment-label"},
	{name: "KubeFeaturePutTemplateFromPod", worth: 500, isA: ["KubeRepairFeature", "Anything"], creditFeatureKey: "kube-feature/v1|put-label|template-label|pod-label"},
	{name: "KubeFeaturePutTemplateFromService", worth: 500, isA: ["KubeRepairFeature", "Anything"], creditFeatureKey: "kube-feature/v1|put-label|template-label|service-label"},
	{name: "KubeFeatureServiceTargetName", worth: 500, isA: ["KubeRepairFeature", "Anything"], creditFeatureKey: "kube-feature/v1|set-port-name|service-target|declared-port"},
	{name: "KubeFeatureServiceTargetNumber", worth: 500, isA: ["KubeRepairFeature", "Anything"], creditFeatureKey: "kube-feature/v1|set-port-number|service-target|declared-port"},
	{name: "KubeFeatureServiceTargetDefault", worth: 500, isA: ["KubeRepairFeature", "Anything"], creditFeatureKey: "kube-feature/v1|unset-service-target|service-target|"},
	{name: "KubeRelationLabelCopy", worth: 500, isA: ["KubeRepairRelation", "Anything"], creditRelationKey: "kube-relation/v1|label-copy|"},
	{name: "KubeRelationReferenceName", worth: 500, isA: ["KubeRepairRelation", "Anything"], creditRelationKey: "kube-relation/v1|reference-to-declared-port|name"},
	{name: "KubeRelationReferenceNumber", worth: 500, isA: ["KubeRepairRelation", "Anything"], creditRelationKey: "kube-relation/v1|reference-to-declared-port|number"},
	{name: "KubeRelationReferenceDefault", worth: 500, isA: ["KubeRepairRelation", "Anything"], creditRelationKey: "kube-relation/v1|reference-to-declared-port|default"},

	{name: "KubeEdit00", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-00", creditFeatureSubject: "KubeFeaturePutTemplateFromDeployment", creditFeatureKey: "kube-feature/v1|put-label|template-label|deployment-label", creditRelationSubject: "KubeRelationLabelCopy", creditRelationKey: "kube-relation/v1|label-copy|", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InB1dC1sYWJlbCIsImRlc3RpbmF0aW9uIjp7ImtpbmQiOiJ0ZW1wbGF0ZS1sYWJlbCIsInJlc291cmNlIjoib3JiaXQiLCJrZXkiOiJhcHAifSwic291cmNlIjp7ImtpbmQiOiJkZXBsb3ltZW50LWxhYmVsIiwicmVzb3VyY2UiOiJvcmJpdCIsImtleSI6ImFwcCJ9fQ\" kube-apply-edit-b64"},
	{name: "KubeEdit01", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-01", creditFeatureSubject: "KubeFeaturePutTemplateFromPod", creditFeatureKey: "kube-feature/v1|put-label|template-label|pod-label", creditRelationSubject: "KubeRelationLabelCopy", creditRelationKey: "kube-relation/v1|label-copy|", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InB1dC1sYWJlbCIsImRlc3RpbmF0aW9uIjp7ImtpbmQiOiJ0ZW1wbGF0ZS1sYWJlbCIsInJlc291cmNlIjoib3JiaXQiLCJrZXkiOiJhcHAifSwic291cmNlIjp7ImtpbmQiOiJwb2QtbGFiZWwiLCJyZXNvdXJjZSI6Im90aGVyIiwia2V5IjoiYXBwIn19\" kube-apply-edit-b64"},
	{name: "KubeEdit02", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-02", creditFeatureSubject: "KubeFeaturePutTemplateFromService", creditFeatureKey: "kube-feature/v1|put-label|template-label|service-label", creditRelationSubject: "KubeRelationLabelCopy", creditRelationKey: "kube-relation/v1|label-copy|", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InB1dC1sYWJlbCIsImRlc3RpbmF0aW9uIjp7ImtpbmQiOiJ0ZW1wbGF0ZS1sYWJlbCIsInJlc291cmNlIjoib3JiaXQiLCJrZXkiOiJhcHAifSwic291cmNlIjp7ImtpbmQiOiJzZXJ2aWNlLWxhYmVsIiwicmVzb3VyY2UiOiJnYXRld2F5Iiwia2V5IjoiYXBwIn19\" kube-apply-edit-b64"},
	{name: "KubeEdit03", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-03", creditFeatureSubject: "KubeFeatureServiceTargetName", creditFeatureKey: "kube-feature/v1|set-port-name|service-target|declared-port", creditRelationSubject: "KubeRelationReferenceName", creditRelationKey: "kube-relation/v1|reference-to-declared-port|name", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InNldC1wb3J0LW5hbWUiLCJkZXN0aW5hdGlvbiI6eyJraW5kIjoic2VydmljZS10YXJnZXQiLCJyZXNvdXJjZSI6ImdhdGV3YXkifSwic291cmNlIjp7ImtpbmQiOiJkZWNsYXJlZC1wb3J0IiwicmVzb3VyY2UiOiJvcmJpdCIsImNvbnRhaW5lciI6InNlcnZlciIsInBvcnQiOiJoZWFsdGgifX0\" kube-apply-edit-b64"},
	{name: "KubeEdit04", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-04", creditFeatureSubject: "KubeFeatureServiceTargetName", creditFeatureKey: "kube-feature/v1|set-port-name|service-target|declared-port", creditRelationSubject: "KubeRelationReferenceName", creditRelationKey: "kube-relation/v1|reference-to-declared-port|name", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InNldC1wb3J0LW5hbWUiLCJkZXN0aW5hdGlvbiI6eyJraW5kIjoic2VydmljZS10YXJnZXQiLCJyZXNvdXJjZSI6ImdhdGV3YXkifSwic291cmNlIjp7ImtpbmQiOiJkZWNsYXJlZC1wb3J0IiwicmVzb3VyY2UiOiJvcmJpdCIsImNvbnRhaW5lciI6InNlcnZlciIsInBvcnQiOiJ3ZWIifX0\" kube-apply-edit-b64"},
	{name: "KubeEdit05", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-05", creditFeatureSubject: "KubeFeatureServiceTargetNumber", creditFeatureKey: "kube-feature/v1|set-port-number|service-target|declared-port", creditRelationSubject: "KubeRelationReferenceNumber", creditRelationKey: "kube-relation/v1|reference-to-declared-port|number", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InNldC1wb3J0LW51bWJlciIsImRlc3RpbmF0aW9uIjp7ImtpbmQiOiJzZXJ2aWNlLXRhcmdldCIsInJlc291cmNlIjoiZ2F0ZXdheSJ9LCJzb3VyY2UiOnsia2luZCI6ImRlY2xhcmVkLXBvcnQiLCJyZXNvdXJjZSI6Im9yYml0IiwiY29udGFpbmVyIjoic2VydmVyIiwicG9ydCI6ImhlYWx0aCJ9fQ\" kube-apply-edit-b64"},
	{name: "KubeEdit06", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-06", creditFeatureSubject: "KubeFeatureServiceTargetNumber", creditFeatureKey: "kube-feature/v1|set-port-number|service-target|declared-port", creditRelationSubject: "KubeRelationReferenceNumber", creditRelationKey: "kube-relation/v1|reference-to-declared-port|number", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InNldC1wb3J0LW51bWJlciIsImRlc3RpbmF0aW9uIjp7ImtpbmQiOiJzZXJ2aWNlLXRhcmdldCIsInJlc291cmNlIjoiZ2F0ZXdheSJ9LCJzb3VyY2UiOnsia2luZCI6ImRlY2xhcmVkLXBvcnQiLCJyZXNvdXJjZSI6Im9yYml0IiwiY29udGFpbmVyIjoic2VydmVyIiwicG9ydCI6IndlYiJ9fQ\" kube-apply-edit-b64"},
	{name: "KubeEdit07", worth: 500, isA: ["KubeAtomicEdit", "UnaryOp", "Op", "Anything"], domain: ["KubeRepairValue"], range: ["KubeRepairValue"], arity: 1, semanticOpcode: "bound-edit-07", creditFeatureSubject: "KubeFeatureServiceTargetDefault", creditFeatureKey: "kube-feature/v1|unset-service-target|service-target|", creditRelationSubject: "KubeRelationReferenceDefault", creditRelationKey: "kube-relation/v1|reference-to-declared-port|default", defn: "\"eyJ2ZXJzaW9uIjoia3ViZXJuZXRlcy1lZGl0L3YxIiwia2luZCI6InVuc2V0LXNlcnZpY2UtdGFyZ2V0IiwiZGVzdGluYXRpb24iOnsia2luZCI6InNlcnZpY2UtdGFyZ2V0IiwicmVzb3VyY2UiOiJnYXRld2F5In19\" kube-apply-edit-b64"},
]
