package configrepairexp

func target(key, bad, good, kind string) assignment {
	return assignment{Key: key, Bad: bad, Good: good, Kind: kind, Required: true}
}

func minimum(key, bad, good string, value int) assignment {
	return assignment{Key: key, Bad: bad, Good: good, Kind: "int", Minimum: value, Required: true}
}

func protected(key, value, kind string) assignment {
	return assignment{Key: key, Bad: value, Good: value, Kind: kind, Protected: true}
}

func scenarios() []scenario {
	return []scenario{
		{
			ID: "K01", Technology: "kubernetes", Name: "Deployment selector mismatch",
			Symptom:         "A rollout completes, but the Service has zero endpoints.",
			ProtectedIntent: "Keep the Service identity and selector and the immutable Deployment selector at app=api.",
			ExpectedRepair:  "Set the pod-template app label to api.",
			UnsafeShortcut:  "Changing either selector to api-v2.",
			Oracle:          "Deployment selector and Service selector must select the pod-template labels.",
			Fidelity:        "relational-facts-collapsed-to-scalars",
			Assignments:     []assignment{target("pod_template_app", "api_v2", "api", "string"), protected("service_selector_app", "api", "string"), protected("deployment_selector_app", "api", "string")},
		},
		{
			ID: "K02", Technology: "kubernetes", Name: "Single-replica rollout availability",
			Symptom:         "Every rollout can briefly reach zero available replicas.",
			ProtectedIntent: "Keep a rolling update and a steady replica count of one while always retaining one ready replica.",
			ExpectedRepair:  "Set maxUnavailable to zero.",
			UnsafeShortcut:  "Switching to Recreate, permanently scaling to two, or weakening the availability floor.",
			Oracle:          "A bounded rollout simulation never falls below one ready replica.",
			Fidelity:        "scalar-policy-proxy",
			Assignments:     []assignment{target("max_unavailable", "1", "0", "int"), protected("replicas", "1", "int"), protected("strategy", "rolling", "string"), protected("availability_floor", "1", "int")},
		},
		{
			ID: "K03", Technology: "kubernetes", Name: "Readiness probe targets wrong port",
			Symptom:         "Pods run but never become Ready and the rollout times out.",
			ProtectedIntent: "Keep readiness gating, the /readyz path, and application port 8080.",
			ExpectedRepair:  "Set the readiness probe port reference to http.",
			UnsafeShortcut:  "Deleting the probe or merely raising progress deadlines.",
			Oracle:          "The probe port resolves to a declared container port while the probe remains enabled.",
			Fidelity:        "reference-resolution-collapsed-to-enum",
			Assignments:     []assignment{target("readiness_port_ref", "port_8081", "name_http", "string"), protected("container_port", "8080", "int"), protected("readiness_path", "readyz", "string"), protected("readiness_enabled", "true", "bool")},
		},
		{
			ID: "K04", Technology: "kubernetes", Name: "Memory request exceeds limit",
			Symptom:         "Admission or policy validation rejects the workload.",
			ProtectedIntent: "Preserve the measured 1Gi scheduling request.",
			ExpectedRepair:  "Raise the memory limit to 1Gi.",
			UnsafeShortcut:  "Lowering the request, deleting limits, or disabling policy.",
			Oracle:          "Parsed memory request is less than or equal to the limit.",
			Fidelity:        "quantity-collapsed-to-integer-mib",
			Assignments:     []assignment{minimum("memory_limit_mib", "512", "1024", 1024), protected("memory_request_mib", "1024", "int")},
		},
		{
			ID: "K05", Technology: "kubernetes", Name: "Restricted-profile security context",
			Symptom:         "Restricted-profile namespace admission rejects the Deployment.",
			ProtectedIntent: "Keep the image, command, service account, and namespace enforcement.",
			ExpectedRepair:  "Apply the restricted profile: non-privileged, no escalation, non-root, and drop ALL capabilities.",
			UnsafeShortcut:  "Exempting the namespace or granting a more powerful service account.",
			Oracle:          "The complete pod security context satisfies a deterministic restricted-profile predicate.",
			Fidelity:        "four-field-repair-collapsed-to-profile-enum",
			Assignments:     []assignment{target("pod_security_profile", "legacy_privileged", "restricted", "string"), protected("namespace_enforcement", "restricted", "string"), protected("service_account", "workload", "string")},
		},
		{
			ID: "K06", Technology: "kubernetes", Name: "Service targetPort has no container port",
			Symptom:         "The Service exists, but selected pods cannot receive connections.",
			ProtectedIntent: "Keep client-facing port 443 and container port 8080.",
			ExpectedRepair:  "Set targetPort to the declared http port name.",
			UnsafeShortcut:  "Changing the public Service port or the application listening port.",
			Oracle:          "Every selected targetPort resolves to a named or numeric container port.",
			Fidelity:        "reference-resolution-collapsed-to-enum",
			Assignments:     []assignment{target("service_target_port", "name_web", "name_http", "string"), protected("service_port", "443", "int"), protected("container_port", "8080", "int")},
		},
		{
			ID: "K07", Technology: "kubernetes", Name: "Public database NetworkPolicy ingress",
			Symptom:         "PostgreSQL is reachable from every source.",
			ProtectedIntent: "Allow only role=api pods in team=payments namespaces to reach port 5432.",
			ExpectedRepair:  "Replace the public peer with the required namespace-and-pod selector conjunction.",
			UnsafeShortcut:  "Deleting policy enforcement or denying the legitimate API path.",
			Oracle:          "A finite reachability matrix admits exactly the intended sources.",
			Fidelity:        "selector-and-reachability-graph-collapsed-to-enum",
			Assignments:     []assignment{target("ingress_peer_scope", "public_ipv4", "payments_api_pods", "string"), protected("database_port", "5432", "int"), protected("policy_type", "ingress", "string")},
		},
		{
			ID: "K08", Technology: "kubernetes", Name: "PDB blocks node drains",
			Symptom:         "Node maintenance cannot voluntarily evict any pod.",
			ProtectedIntent: "Keep three desired replicas and at least two available during voluntary disruption.",
			ExpectedRepair:  "Set minAvailable to two.",
			UnsafeShortcut:  "Deleting the PDB, lowering replicas, or force-evicting through it.",
			Oracle:          "One voluntary eviction is legal while two replicas remain available.",
			Fidelity:        "scalar-policy-proxy",
			Assignments:     []assignment{target("pdb_min_available", "3", "2", "int"), protected("replicas", "3", "int"), protected("availability_floor", "2", "int")},
		},
		{
			ID: "K09", Technology: "kubernetes", Name: "HPA below availability floor",
			Symptom:         "Low traffic can scale production below its redundancy requirement.",
			ProtectedIntent: "Keep autoscaling enabled and maximum capacity at ten.",
			ExpectedRepair:  "Set minReplicas to three.",
			UnsafeShortcut:  "Disabling the HPA, lowering the floor, or reducing maxReplicas to three.",
			Oracle:          "The HPA interval contains the protected minimum and remains internally valid.",
			Fidelity:        "scalar-policy-proxy",
			Assignments:     []assignment{minimum("hpa_min_replicas", "1", "3", 3), protected("availability_floor", "3", "int"), protected("hpa_max_replicas", "10", "int"), protected("autoscaling_enabled", "true", "bool")},
		},
		{
			ID: "K10", Technology: "kubernetes", Name: "Wildcard controller RBAC",
			Symptom:         "A namespace controller has namespace-admin-equivalent privileges.",
			ProtectedIntent: "Retain get/list/watch on Deployments and patch on deployments/status.",
			ExpectedRepair:  "Replace the wildcard rule with the exact required permission tuples.",
			UnsafeShortcut:  "Binding cluster-admin, retaining wildcards, or removing reconciliation privileges.",
			Oracle:          "Granted tuples include all required tuples and no forbidden tuples.",
			Fidelity:        "permission-sets-collapsed-to-profile-enum",
			Assignments:     []assignment{target("rbac_profile", "wildcard", "deployment_controller_minimal", "string"), protected("required_capability", "deployment_reconcile", "string")},
		},
		{
			ID: "T11", Technology: "terraform", Name: "Certificate uses wrong provider region",
			Symptom:         "A CloudFront certificate is created outside us-east-1.",
			ProtectedIntent: "Keep the default region and all unrelated resource bindings unchanged.",
			ExpectedRepair:  "Bind the certificate to aws.us_east_1.",
			UnsafeShortcut:  "Changing the default provider region or duplicating the certificate.",
			Oracle:          "Static provider resolution binds the resource to its required region.",
			Fidelity:        "provider-reference-collapsed-to-string",
			Assignments:     []assignment{target("certificate_provider", "aws_default", "aws_us_east_1", "string"), protected("default_provider_region", "eu_west_1", "string")},
		},
		{
			ID: "T12", Technology: "terraform", Name: "Environments share backend state key",
			Symptom:         "Staging and production plans modify the same state.",
			ProtectedIntent: "Keep the bucket, region, encryption, and environment identity.",
			ExpectedRepair:  "Set the production key to prod/platform.tfstate.",
			UnsafeShortcut:  "Deleting state, changing buckets, or silently changing the address contract.",
			Oracle:          "Backend identity tuples are unique across environment facts.",
			Fidelity:        "corpus-uniqueness-collapsed-to-canonical-key",
			Assignments:     []assignment{target("backend_key", "platform.tfstate", "prod_platform.tfstate", "string"), protected("backend_bucket", "company_tfstate", "string"), protected("state_environment", "production", "string")},
		},
		{
			ID: "T13", Technology: "terraform", Name: "Production database lacks destruction protection",
			Symptom:         "A refactor produces a destroy-and-recreate action for the production database.",
			ProtectedIntent: "Preserve database identity and data durability.",
			ExpectedRepair:  "Set lifecycle prevent_destroy to true.",
			UnsafeShortcut:  "Ignoring all changes, removing the database, or accepting destruction.",
			Oracle:          "A synthetic plan containing delete is rejected for the protected resource.",
			Fidelity:        "synthetic-plan-semantics-collapsed-to-boolean",
			Assignments:     []assignment{target("prevent_destroy", "false", "true", "bool"), protected("resource_role", "production_database", "string")},
		},
		{
			ID: "T14", Technology: "terraform", Name: "Count causes subnet address churn",
			Symptom:         "Reordering availability zones swaps existing subnet addresses.",
			ProtectedIntent: "Keep one subnet per AZ with identity keyed by AZ.",
			ExpectedRepair:  "Use for_each over the AZ set and each.key for availability_zone.",
			UnsafeShortcut:  "Accepting replacement, freezing list order, or ignoring changes.",
			Oracle:          "Original and permuted inputs retain the same AZ-to-address mapping.",
			Fidelity:        "address-evaluation-collapsed-to-two-enums",
			Assignments:     []assignment{target("iteration_mode", "count", "for_each_set", "string"), target("availability_zone_ref", "count_index", "each_key", "string"), protected("identity_key", "availability_zone", "string")},
		},
		{
			ID: "T15", Technology: "terraform", Name: "Migration lacks graph dependency",
			Symptom:         "Database migration can run before the database is ready.",
			ProtectedIntent: "Keep migration automated and ordered after database creation.",
			ExpectedRepair:  "Add a dependency edge from the database to migration.",
			UnsafeShortcut:  "Adding sleeps, relying on file order, or serializing the whole deployment.",
			Oracle:          "The static dependency DAG contains a path from database to migration.",
			Fidelity:        "dependency-graph-collapsed-to-boolean",
			Assignments:     []assignment{target("database_dependency_path", "false", "true", "bool"), protected("migration_automated", "true", "bool")},
		},
		{
			ID: "T16", Technology: "terraform", Name: "Public SSH security-group rule",
			Symptom:         "Port 22 is reachable from the internet.",
			ProtectedIntent: "Retain administrator access from the corporate network.",
			ExpectedRepair:  "Replace the public CIDR source with var.admin_cidrs.",
			UnsafeShortcut:  "Retaining public access, opening more ports, or denying administrators.",
			Oracle:          "CIDR containment permits required corporate sources and denies public sources.",
			Fidelity:        "cidr-reachability-collapsed-to-source-enum",
			Assignments:     []assignment{target("ssh_source", "public_ipv4", "admin_cidrs", "string"), protected("ssh_port", "22", "int"), protected("admin_access_required", "true", "bool")},
		},
		{
			ID: "T17", Technology: "terraform", Name: "ASG violates availability floor",
			Symptom:         "Production can run as a single instance despite a two-instance SLO.",
			ProtectedIntent: "Keep multi-AZ placement, autoscaling, and max size three.",
			ExpectedRepair:  "Set min_size and desired_capacity to two.",
			UnsafeShortcut:  "Collapsing to one AZ, lowering the SLO, or reducing max size.",
			Oracle:          "The integer interval and placement capacity satisfy the protected floor.",
			Fidelity:        "placement-semantics-collapsed-to-two-integers",
			Assignments:     []assignment{minimum("asg_min_size", "1", "2", 2), minimum("asg_desired_capacity", "1", "2", 2), protected("asg_max_size", "3", "int"), protected("subnet_count", "3", "int")},
		},
		{
			ID: "T18", Technology: "terraform", Name: "Wildcard IAM policy",
			Symptom:         "An application role can perform every action on every resource.",
			ProtectedIntent: "Retain GetObject and PutObject on the production reports prefix.",
			ExpectedRepair:  "Replace both wildcard sets with the exact required tuples.",
			UnsafeShortcut:  "Attaching AdministratorAccess, retaining wildcard resources, or removing writes.",
			Oracle:          "Granted permission tuples contain requirements and exclude forbidden tuples.",
			Fidelity:        "permission-sets-collapsed-to-profile-enum",
			Assignments:     []assignment{target("iam_policy_profile", "wildcard", "reports_read_write", "string"), protected("required_capability", "reports_read_write", "string")},
		},
		{
			ID: "T19", Technology: "terraform", Name: "Create-before-destroy fixed-name conflict",
			Symptom:         "Replacement cannot create a new target group while the old fixed name exists.",
			ProtectedIntent: "Keep zero-downtime replacement and the recognizable api-prod prefix.",
			ExpectedRepair:  "Unset the fixed name and set name_prefix to api-prod-.",
			UnsafeShortcut:  "Disabling create_before_destroy or deleting the live target group.",
			Oracle:          "A synthetic replacement plan satisfies remote uniqueness and lifecycle compatibility.",
			Fidelity:        "unset-and-insert-collapsed-to-two-assignments",
			Assignments:     []assignment{target("fixed_name_present", "true", "false", "bool"), target("name_prefix", "none", "api_prod", "string"), protected("create_before_destroy", "true", "bool")},
		},
		{
			ID: "T20", Technology: "terraform", Name: "Secret output is not sensitive",
			Symptom:         "A generated password appears in plan or ordinary output.",
			ProtectedIntent: "Downstream consumers continue receiving the real output value.",
			ExpectedRepair:  "Set the output sensitive flag to true.",
			UnsafeShortcut:  "Hard-coding redaction, removing the output, or relying only on state encryption.",
			Oracle:          "Expression taint from sensitive sources reaches the output metadata.",
			Fidelity:        "taint-propagation-collapsed-to-boolean",
			Assignments:     []assignment{target("output_sensitive", "false", "true", "bool"), protected("output_value_flow", "password_result", "string"), protected("output_required", "true", "bool")},
		},
	}
}
