package causalexpv2

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

type EvidenceBytes struct {
	Report []byte
	Bundle []byte
}

// PublishTrainingEvidence verifies the two final canonical byte strings, writes
// them into one absent sibling staging directory, fsyncs and reopens both, then
// performs one no-replace directory rename. It never resumes staging bytes.
func (cap *attemptCapability) publishTrainingEvidence(repoRoot string, evidence EvidenceBytes) error {
	if cap == nil {
		return errors.New("missing training attempt capability")
	}
	if cap.replayOnly {
		return errors.New("replay regeneration has no training publication authority")
	}
	cap.mu.Lock()
	if cap.consumed || cap.record.Panel != PanelTraining || cap.record.State != "started" {
		cap.mu.Unlock()
		return errors.New("invalid training publication capability")
	}
	if len(cap.generated) != cap.record.SeedRange.Count {
		cap.mu.Unlock()
		return errors.New("attempt has not generated its complete seed range")
	}
	cap.mu.Unlock()
	fail := func(cause error) error {
		if transitionErr := writeAttemptState(cap, "failed"); transitionErr != nil {
			return fmt.Errorf("%w; also failed to preserve attempt failure: %v", cause, transitionErr)
		}
		return cause
	}
	state, err := resolveGitState(context.Background(), repoRoot)
	if err != nil {
		return fail(err)
	}
	if state.Root != cap.repositoryRoot || state.CommonDir != cap.commonDirectory || !state.Clean || state.Head != cap.record.ExecutableCommit {
		return fail(errors.New("training publication is not bound to its same clean pretraining repository"))
	}

	verified, err := contextuallyVerifyTrainingEvidence(context.Background(), state.Root, evidence.Report, evidence.Bundle)
	if err != nil {
		return fail(err)
	}
	report, bundle := verified.Report, verified.Bundle
	for _, fixture := range bundle.Fixtures {
		if cap.generated[fixture.PublicFixture.Seed] != fixture.PublicFixture.FixtureDigest {
			return fail(errors.New("training bundle fixture digest was not generated by this attempt"))
		}
	}
	cap.mu.Lock()
	expectedReportDigest, expectedBundleDigest := cap.expectedReportDigest, cap.expectedBundleDigest
	cap.mu.Unlock()
	if expectedReportDigest == "" || expectedBundleDigest == "" || report.TrainingDigest != expectedReportDigest || bundle.BundleDigest != expectedBundleDigest || report.EpisodeBundleDigest != bundle.BundleDigest || report.EpisodeBundleBytes != len(evidence.Bundle) {
		return fail(errors.New("training report does not bind bundle bytes"))
	}
	finalDirectory := filepath.Join(repoRoot, TrainingEvidenceDirectory)
	parent := filepath.Dir(finalDirectory)
	staging := filepath.Join(parent, ".active-causal-diagnosis-v2.staging")
	if err := requireAbsent(finalDirectory); err != nil {
		return fail(err)
	}
	if err := os.Mkdir(staging, 0o700); err != nil {
		return fail(fmt.Errorf("create exclusive evidence staging directory: %w", err))
	}
	if err := writeExclusiveSynced(filepath.Join(staging, TrainingReportName), evidence.Report); err != nil {
		return fail(err)
	}
	if err := writeExclusiveSynced(filepath.Join(staging, TrainingEpisodesName), evidence.Bundle); err != nil {
		return fail(err)
	}
	if err := syncDirectory(staging); err != nil {
		return fail(err)
	}
	for name, want := range map[string][]byte{TrainingReportName: evidence.Report, TrainingEpisodesName: evidence.Bundle} {
		got, readErr := os.ReadFile(filepath.Join(staging, name))
		if readErr != nil || !bytes.Equal(got, want) {
			return fail(fmt.Errorf("staged %s failed byte-for-byte reopen", name))
		}
	}
	if err := renameNoReplace(staging, finalDirectory); err != nil {
		return fail(fmt.Errorf("publish evidence directory: %w", err))
	}
	if err := syncDirectory(parent); err != nil {
		return fail(err)
	}
	cap.mu.Lock()
	cap.proof.PublishedDigest = report.TrainingDigest
	if err := persistAttemptProofLocked(cap); err != nil {
		cap.mu.Unlock()
		return fail(err)
	}
	cap.mu.Unlock()
	return writeAttemptState(cap, "published")
}

func requireAbsent(path string) error {
	if _, err := os.Lstat(path); err == nil {
		return fmt.Errorf("path already exists: %s", path)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

func writeExclusiveSynced(path string, data []byte) error {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}
	if _, err = file.Write(data); err == nil {
		err = file.Sync()
	}
	closeErr := file.Close()
	if err == nil {
		err = closeErr
	}
	return err
}
